theme: jekyll-theme-slate
title: João Gabriel
description: A Processing developer (and maybe some other stuff).
github:
  repository_url: none
syntax-highlighting:
  enabled : true
  css: syntax.css

