title: João Gabriel
description: A Processing developer (and maybe some other stuff).
github:
  repository_url: https://github.com/joogps
syntax-highlighting:
  enabled : true
  css: syntax.css
theme: jekyll-theme-slate
