title: João Gabriel
description: Um desenvolvedor em Processing (e talvez umas outras coisinhas).
github:
  is_project_page: false
  repository_url: https://github.com/joogps
syntax-highlighting:
  enabled : true
  css: syntax.css
theme: jekyll-theme-slate